### PR TITLE
Gem::Specification.load causes "No such file or directory - git" error at run time

### PR DESCRIPTION
**Pull request by asannou**
```
$ docker run -it ruby:slim bash
root@b17daa5fc5bc:/# gem install aws-ssm-console
Fetching: jmespath-1.3.1.gem (100%)
Successfully installed jmespath-1.3.1
Fetching: aws-sigv4-1.0.0.gem (100%)
Successfully installed aws-sigv4-1.0.0
Fetching: aws-sdk-core-2.6.39.gem (100%)
Successfully installed aws-sdk-core-2.6.39
Fetching: aws-sdk-resources-2.6.39.gem (100%)
Successfully installed aws-sdk-resources-2.6.39
Fetching: aws-sdk-2.6.39.gem (100%)
Successfully installed aws-sdk-2.6.39
Fetching: aws-ssm-console-0.2.2.gem (100%)
Successfully installed aws-ssm-console-0.2.2
6 gems installed
root@b17daa5fc5bc:/# aws-ssm-console -h
Invalid gemspec in [/usr/local/bundle/gems/aws-ssm-console-0.2.2/aws-ssm-console.gemspec]: No such file or directory - git
/usr/local/bundle/gems/aws-ssm-console-0.2.2/lib/aws/ssm/console/version.rb:6:in `<module:Console>': undefined method `version' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/aws-ssm-console-0.2.2/lib/aws/ssm/console/version.rb:3:in `<module:SSM>'
	from /usr/local/bundle/gems/aws-ssm-console-0.2.2/lib/aws/ssm/console/version.rb:2:in `<module:Aws>'
	from /usr/local/bundle/gems/aws-ssm-console-0.2.2/lib/aws/ssm/console/version.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/aws-ssm-console-0.2.2/lib/aws/ssm/console.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/aws-ssm-console-0.2.2/exe/aws-ssm-console:6:in `<top (required)>'
	from /usr/local/bundle/bin/aws-ssm-console:22:in `load'
	from /usr/local/bundle/bin/aws-ssm-console:22:in `<main>'
```

### CODE REVIEW

**Comment by koshigoe** [comment]
Thanks!

> `git ls-files -z`

Oh, I see. Certainly, it requires `git` command...

Hmm...

I think it cause other problem:

```
Failures:

  1) Aws::SSM::Console.client
     Failure/Error: @client ||= Aws::SSM::Client.new

     NameError:
       uninitialized constant Aws::SSM::Client
       Did you mean?  Aws::Client
     # ./lib/aws/ssm/console.rb:13:in `client'
     # ./spec/aws/ssm/console_spec.rb:9:in `block (3 levels) in <top (required)>'
     # ./spec/aws/ssm/console_spec.rb:11:in `block (3 levels) in <top (required)>'

Finished in 0.17046 seconds (files took 0.14182 seconds to load)
11 examples, 1 failure

Failed examples:

rspec ./spec/aws/ssm/console_spec.rb:11 # Aws::SSM::Console.client

```

`Aws::SSM::Client` is a class included `aws-sdk` gem.

**Comment by koshigoe** [comment]
I'm using bad namespace...

**Comment by koshigoe** [comment]
I don't have good idea to resolve `uninitialized constant Aws::SSM::Client` now.

So, I think:

- keep chages of `lib/aws/ssm/console/version.rb`
- revert chages of `aws-ssm-console.gemspec`

Not DRY, but I think easy way to resolve problem.

**Comment by asannou** [comment]
How is this?

**Comment by koshigoe** [comment]
I think it's ok.

But, it require aws-sdk before specify dependency in gemspec.
Is it ok?
I don't know.

**Comment by asannou** [comment]
`require 'aws-sdk'` deleted.

**Comment by koshigoe** [comment]
Thank you for your idea!!
Hmm.., but I think it's too much.

I try fixing this problem (https://github.com/koshigoe/aws-ssm-console/pull/9) in reference to [`aws-sdk-rails`](https://github.com/aws/aws-sdk-rails/blob/master/aws-sdk-rails.gemspec#L1-L3).

Thank you very much!!

P.S. Can you check my branch? (https://github.com/koshigoe/aws-ssm-console/pull/9)

**Comment by asannou** [comment]
Okay.
I think #9 is a simple and good solution.

**Comment by koshigoe** [comment]
Thanks!!

I merged #9. So I close this PR.

**Pull request closed without merging**
